### ISSUE TITLE
Only audio is downloaded

### ISSUE THREAD

**Issue by beutepa** [d0u9/docker#1]
I'm running the youtube-dl-webui  docker container, but only audio is downloaded...

I tried with serveral files (and formats) that work using the command-line version of youtube-dl, e.g. https://www.youtube.com/watch?v=cYd5Mb90V5w

Content of the 'Status' in the web ui:  
```
Title:
4K UHD Test Pattern H 264 MP4 hd720
Extension:
m4a
Format:
140 - audio only (DASH audio)
Create Time:
‎Aug‎ ‎22‎, ‎2017‎ ‎01‎:‎26‎:‎57
Finish Time:
‎Aug‎ ‎22‎, ‎2017‎ ‎01‎:‎27‎:‎02
File Name:
4K UHD Test Pattern H 264 MP4 hd720-cYd5Mb90V5w.m4a
```

Any idea why this would happen?

My configuration: youtube-dl-webui.json
```
{
    "general": {
        "download_dir": "/tmp/youtube_dl",
        "db_path": "/tmp/youtube_dl_webui.db",
        "download_log_size": 10
    },
    "server": {
        "host": "0.0.0.0",
        "port": 5000
    },
    "youtube_dl": {
        "format": "bestaudio/best"
    }
}
```

My docker run statement:
```
docker run -d \
--name ytl \
-e CONF_FILE=/etc/youtube-dl-webui.json \
-v /home/<username>/docker/youtube-dl-webui/youtube-dl-webui.json:/etc/youtube-dl-webui.json \
-v /home/<username>/docker/youtube-dl-webui/data:/tmp/youtube_dl \
-p 5000:5000 \
d0u9/youtube-dl-webui
```

**Comment by d0u9** [comment]
Sorry for my late replay.

You have set the format in **youtube-dl-webui.json** as `bestaudio/best`. This makes youtube-dl try to download `bestaudio` format first, that is why you have audio only downloaded. For more information about format selection, check [youtube-dl's official documentation](https://github.com/rg3/youtube-dl#format-selection).

So, set this option to `best` will solve this problem. Notably, for downloading high resolution format, the video and audio will be downloaded separately, and be merged in the post staged. However, I have't implemented this feature in my **youtube-dl-webui** project.

**Comment by beutepa** [comment]
This was indeed the issue. Thx!
